// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: billingserver/billing.proto

package billingserver

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CostUsageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionID string `protobuf:"bytes,1,opt,name=subscriptionID,proto3" json:"subscriptionID,omitempty"`
}

func (x *CostUsageRequest) Reset() {
	*x = CostUsageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billingserver_billing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostUsageRequest) ProtoMessage() {}

func (x *CostUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billingserver_billing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostUsageRequest.ProtoReflect.Descriptor instead.
func (*CostUsageRequest) Descriptor() ([]byte, []int) {
	return file_billingserver_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CostUsageRequest) GetSubscriptionID() string {
	if x != nil {
		return x.SubscriptionID
	}
	return ""
}

type CostUsageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionID  string `protobuf:"bytes,1,opt,name=subscriptionID,proto3" json:"subscriptionID,omitempty"`
	AccumulatedCost string `protobuf:"bytes,2,opt,name=accumulatedCost,proto3" json:"accumulatedCost,omitempty"`
}

func (x *CostUsageResponse) Reset() {
	*x = CostUsageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billingserver_billing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostUsageResponse) ProtoMessage() {}

func (x *CostUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billingserver_billing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostUsageResponse.ProtoReflect.Descriptor instead.
func (*CostUsageResponse) Descriptor() ([]byte, []int) {
	return file_billingserver_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CostUsageResponse) GetSubscriptionID() string {
	if x != nil {
		return x.SubscriptionID
	}
	return ""
}

func (x *CostUsageResponse) GetAccumulatedCost() string {
	if x != nil {
		return x.AccumulatedCost
	}
	return ""
}

var File_billingserver_billing_proto protoreflect.FileDescriptor

var file_billingserver_billing_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x10,
	0x43, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x65, 0x0a, 0x11, 0x43, 0x6f, 0x73, 0x74,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x73, 0x74, 0x32,
	0x66, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x5b, 0x0a, 0x10, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x1f,
	0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_billingserver_billing_proto_rawDescOnce sync.Once
	file_billingserver_billing_proto_rawDescData = file_billingserver_billing_proto_rawDesc
)

func file_billingserver_billing_proto_rawDescGZIP() []byte {
	file_billingserver_billing_proto_rawDescOnce.Do(func() {
		file_billingserver_billing_proto_rawDescData = protoimpl.X.CompressGZIP(file_billingserver_billing_proto_rawDescData)
	})
	return file_billingserver_billing_proto_rawDescData
}

var file_billingserver_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billingserver_billing_proto_goTypes = []interface{}{
	(*CostUsageRequest)(nil),  // 0: billingserver.CostUsageRequest
	(*CostUsageResponse)(nil), // 1: billingserver.CostUsageResponse
}
var file_billingserver_billing_proto_depIdxs = []int32{
	0, // 0: billingserver.Billing.subscriptionCost:input_type -> billingserver.CostUsageRequest
	1, // 1: billingserver.Billing.subscriptionCost:output_type -> billingserver.CostUsageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billingserver_billing_proto_init() }
func file_billingserver_billing_proto_init() {
	if File_billingserver_billing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_billingserver_billing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostUsageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billingserver_billing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostUsageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_billingserver_billing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billingserver_billing_proto_goTypes,
		DependencyIndexes: file_billingserver_billing_proto_depIdxs,
		MessageInfos:      file_billingserver_billing_proto_msgTypes,
	}.Build()
	File_billingserver_billing_proto = out.File
	file_billingserver_billing_proto_rawDesc = nil
	file_billingserver_billing_proto_goTypes = nil
	file_billingserver_billing_proto_depIdxs = nil
}
