# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='database.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x61tabase.proto\"\x1f\n\rDbListRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"I\n\rDbAuthRequest\x12\x14\n\x0c\x64\x61tabaseName\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"T\n\x0f\x44\x62UploadRequest\x12\x14\n\x0c\x64\x61tabaseName\x18\x01 \x01(\t\x12\x15\n\rdatabaseToken\x18\x02 \x01(\t\x12\x14\n\x0cpayloadChunk\x18\x03 \x01(\t\"U\n\x0e\x44\x62ListResponse\x12\x14\n\x0c\x64\x61tabaseName\x18\x01 \x01(\t\x12\x17\n\x0fresponseMessage\x18\x04 \x01(\t\x12\x14\n\x0cresponseCode\x18\x05 \x01(\x05\"V\n\x0e\x44\x62\x41uthResponse\x12\x15\n\rdatabaseToken\x18\x01 \x01(\t\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\x12\x14\n\x0cresponseCode\x18\x03 \x01(\x05\"A\n\x10\x44\x62UploadResponse\x12\x17\n\x0fresponseMessage\x18\x01 \x01(\t\x12\x14\n\x0cresponseCode\x18\x02 \x01(\x05\x32\xb0\x01\n\x0f\x44\x61tabaseService\x12\x32\n\rlistDatabases\x12\x0e.DbListRequest\x1a\x0f.DbListResponse0\x01\x12\x30\n\rdatabaseLogin\x12\x0e.DbAuthRequest\x1a\x0f.DbAuthResponse\x12\x37\n\x0e\x64\x61tabaseUpload\x12\x10.DbUploadRequest\x1a\x11.DbUploadResponse(\x01\x62\x06proto3'
)




_DBLISTREQUEST = _descriptor.Descriptor(
  name='DbListRequest',
  full_name='DbListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='DbListRequest.region', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_DBAUTHREQUEST = _descriptor.Descriptor(
  name='DbAuthRequest',
  full_name='DbAuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='databaseName', full_name='DbAuthRequest.databaseName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userName', full_name='DbAuthRequest.userName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='DbAuthRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=124,
)


_DBUPLOADREQUEST = _descriptor.Descriptor(
  name='DbUploadRequest',
  full_name='DbUploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='databaseName', full_name='DbUploadRequest.databaseName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='databaseToken', full_name='DbUploadRequest.databaseToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payloadChunk', full_name='DbUploadRequest.payloadChunk', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=210,
)


_DBLISTRESPONSE = _descriptor.Descriptor(
  name='DbListResponse',
  full_name='DbListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='databaseName', full_name='DbListResponse.databaseName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='DbListResponse.responseMessage', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='DbListResponse.responseCode', index=2,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=297,
)


_DBAUTHRESPONSE = _descriptor.Descriptor(
  name='DbAuthResponse',
  full_name='DbAuthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='databaseToken', full_name='DbAuthResponse.databaseToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='DbAuthResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='DbAuthResponse.responseCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=385,
)


_DBUPLOADRESPONSE = _descriptor.Descriptor(
  name='DbUploadResponse',
  full_name='DbUploadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='DbUploadResponse.responseMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='DbUploadResponse.responseCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=452,
)

DESCRIPTOR.message_types_by_name['DbListRequest'] = _DBLISTREQUEST
DESCRIPTOR.message_types_by_name['DbAuthRequest'] = _DBAUTHREQUEST
DESCRIPTOR.message_types_by_name['DbUploadRequest'] = _DBUPLOADREQUEST
DESCRIPTOR.message_types_by_name['DbListResponse'] = _DBLISTRESPONSE
DESCRIPTOR.message_types_by_name['DbAuthResponse'] = _DBAUTHRESPONSE
DESCRIPTOR.message_types_by_name['DbUploadResponse'] = _DBUPLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbListRequest = _reflection.GeneratedProtocolMessageType('DbListRequest', (_message.Message,), {
  'DESCRIPTOR' : _DBLISTREQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:DbListRequest)
  })
_sym_db.RegisterMessage(DbListRequest)

DbAuthRequest = _reflection.GeneratedProtocolMessageType('DbAuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _DBAUTHREQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:DbAuthRequest)
  })
_sym_db.RegisterMessage(DbAuthRequest)

DbUploadRequest = _reflection.GeneratedProtocolMessageType('DbUploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _DBUPLOADREQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:DbUploadRequest)
  })
_sym_db.RegisterMessage(DbUploadRequest)

DbListResponse = _reflection.GeneratedProtocolMessageType('DbListResponse', (_message.Message,), {
  'DESCRIPTOR' : _DBLISTRESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:DbListResponse)
  })
_sym_db.RegisterMessage(DbListResponse)

DbAuthResponse = _reflection.GeneratedProtocolMessageType('DbAuthResponse', (_message.Message,), {
  'DESCRIPTOR' : _DBAUTHRESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:DbAuthResponse)
  })
_sym_db.RegisterMessage(DbAuthResponse)

DbUploadResponse = _reflection.GeneratedProtocolMessageType('DbUploadResponse', (_message.Message,), {
  'DESCRIPTOR' : _DBUPLOADRESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:DbUploadResponse)
  })
_sym_db.RegisterMessage(DbUploadResponse)



_DATABASESERVICE = _descriptor.ServiceDescriptor(
  name='DatabaseService',
  full_name='DatabaseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=455,
  serialized_end=631,
  methods=[
  _descriptor.MethodDescriptor(
    name='listDatabases',
    full_name='DatabaseService.listDatabases',
    index=0,
    containing_service=None,
    input_type=_DBLISTREQUEST,
    output_type=_DBLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='databaseLogin',
    full_name='DatabaseService.databaseLogin',
    index=1,
    containing_service=None,
    input_type=_DBAUTHREQUEST,
    output_type=_DBAUTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='databaseUpload',
    full_name='DatabaseService.databaseUpload',
    index=2,
    containing_service=None,
    input_type=_DBUPLOADREQUEST,
    output_type=_DBUPLOADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASESERVICE)

DESCRIPTOR.services_by_name['DatabaseService'] = _DATABASESERVICE

# @@protoc_insertion_point(module_scope)
