# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compute.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcompute.proto\"\x1b\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0cImageRequest\x12\x12\n\nregionName\x18\x01 \x01(\t\"3\n\x0f\x43\x61pacityRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x10\n\x08\x63puCount\x18\x02 \x01(\x05\"V\n\x0cNameResponse\x12\x17\n\x0fvalidNameChoice\x18\x01 \x01(\x08\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\x12\x14\n\x0cresponseCode\x18\x03 \x01(\x05\"Q\n\rImageResponse\x12\x11\n\timageName\x18\x01 \x01(\t\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\x12\x14\n\x0cresponseCode\x18\x03 \x01(\x05\"z\n\x10\x43\x61pacityResponse\x12\x1c\n\x14\x63\x61pacityAvailability\x18\x01 \x01(\x08\x12\x19\n\x11\x63puCoresAvailable\x18\x02 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\x12\x14\n\x0cresponseCode\x18\x04 \x01(\x05\x32\xa9\x01\n\x0e\x43omputeService\x12+\n\x0cvalidateName\x12\x0c.NameRequest\x1a\r.NameResponse\x12\x31\n\x0eretrieveImages\x12\r.ImageRequest\x1a\x0e.ImageResponse0\x01\x12\x37\n\x10validateCapacity\x12\x10.CapacityRequest\x1a\x11.CapacityResponseb\x06proto3'
)




_NAMEREQUEST = _descriptor.Descriptor(
  name='NameRequest',
  full_name='NameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=44,
)


_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regionName', full_name='ImageRequest.regionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=80,
)


_CAPACITYREQUEST = _descriptor.Descriptor(
  name='CapacityRequest',
  full_name='CapacityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='CapacityRequest.region', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpuCount', full_name='CapacityRequest.cpuCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=133,
)


_NAMERESPONSE = _descriptor.Descriptor(
  name='NameResponse',
  full_name='NameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='validNameChoice', full_name='NameResponse.validNameChoice', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='NameResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='NameResponse.responseCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=221,
)


_IMAGERESPONSE = _descriptor.Descriptor(
  name='ImageResponse',
  full_name='ImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageName', full_name='ImageResponse.imageName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='ImageResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='ImageResponse.responseCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=304,
)


_CAPACITYRESPONSE = _descriptor.Descriptor(
  name='CapacityResponse',
  full_name='CapacityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capacityAvailability', full_name='CapacityResponse.capacityAvailability', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpuCoresAvailable', full_name='CapacityResponse.cpuCoresAvailable', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='CapacityResponse.responseMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='CapacityResponse.responseCode', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['NameRequest'] = _NAMEREQUEST
DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['CapacityRequest'] = _CAPACITYREQUEST
DESCRIPTOR.message_types_by_name['NameResponse'] = _NAMERESPONSE
DESCRIPTOR.message_types_by_name['ImageResponse'] = _IMAGERESPONSE
DESCRIPTOR.message_types_by_name['CapacityResponse'] = _CAPACITYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAMEREQUEST,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:NameRequest)
  })
_sym_db.RegisterMessage(NameRequest)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

CapacityRequest = _reflection.GeneratedProtocolMessageType('CapacityRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAPACITYREQUEST,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:CapacityRequest)
  })
_sym_db.RegisterMessage(CapacityRequest)

NameResponse = _reflection.GeneratedProtocolMessageType('NameResponse', (_message.Message,), {
  'DESCRIPTOR' : _NAMERESPONSE,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:NameResponse)
  })
_sym_db.RegisterMessage(NameResponse)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

CapacityResponse = _reflection.GeneratedProtocolMessageType('CapacityResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAPACITYRESPONSE,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:CapacityResponse)
  })
_sym_db.RegisterMessage(CapacityResponse)



_COMPUTESERVICE = _descriptor.ServiceDescriptor(
  name='ComputeService',
  full_name='ComputeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=431,
  serialized_end=600,
  methods=[
  _descriptor.MethodDescriptor(
    name='validateName',
    full_name='ComputeService.validateName',
    index=0,
    containing_service=None,
    input_type=_NAMEREQUEST,
    output_type=_NAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='retrieveImages',
    full_name='ComputeService.retrieveImages',
    index=1,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='validateCapacity',
    full_name='ComputeService.validateCapacity',
    index=2,
    containing_service=None,
    input_type=_CAPACITYREQUEST,
    output_type=_CAPACITYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTESERVICE)

DESCRIPTOR.services_by_name['ComputeService'] = _COMPUTESERVICE

# @@protoc_insertion_point(module_scope)
